const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');

require('dotenv').config();
const environment = argv.environment;

function writeFileUsingFS(path: string, envFileContent: string): void {
  writeFile(path, envFileContent, (err: Error) => {
    if (err) {
      console.log(err);
    }
    if (envFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
}

// Providing path to the `environments` directory
const envDirectory = './src/environments';

// creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

// creates the `environment.prod.ts` and `environment.ts` file if it does not exist
writeFileUsingFS('./src/environments/environment.prod.ts', '');
writeFileUsingFS('./src/environments/environment.ts', '');

// Checks whether command line argument of `prod` was provided signifying production mode
const isProduction = environment === 'prod';

// choose the correct targetPath based on the environment chosen
const targetPath = isProduction
  ? './src/environments/environment.prod.ts'
  : './src/environments/environment.ts';

// actual content to be compiled dynamically and pasted into respective environment files
const environmentFileContent = `
      // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
      export const environment = {
        production: ${isProduction},
        ROOT_PATH: '${isProduction ? process.env.ROOT_PATH_PROD : process.env.ROOT_PATH_DEV}',
      };`;

writeFileUsingFS(targetPath, environmentFileContent); // appending data into the target file
